# Generated by Django 4.0.5 on 2022-06-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b3', models.CharField(max_length=10)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('desc_empresa', models.CharField(blank=True, max_length=200)),
                ('lim_inf', models.FloatField()),
                ('lim_sup', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('porcentagem', models.FloatField()),
                ('valor_anterior', models.FloatField()),
                ('ultimo_hist', models.BooleanField(null=True)),
                ('fk_ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ativo')),
            ],
        ),
    ]
